# Botón "Sponsor" del repo.
# Docs: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

ko_fi: aurealnix
# github: [ut-slayer]   # descoméntalo cuando actives GitHub Sponsors
